FROM python:3.12-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-cache

COPY ./src /app/src


RUN  uv pip install docling --extra-index-url https://download.pytorch.org/whl/cpu

EXPOSE 8000

CMD [ "uv", "uvicorn", "src.api.v1.main:app", "--host", "0.0.0.0", "--port", "8000" ]