services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=otis
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: otis-api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    env_file:
      - .env
      - .env.fastapi
    depends_on:
      - db
    command: uv run uvicorn src.api.v1.main:app --host 0.0.0.0 --port 8000 --reload
